In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder,TargetEncoder,StandardScaler,MinMaxScaler
from sklearn.impute import SimpleImputer

In [7]:
df=pd.read_csv("C:/Users/Gyanp/Downloads/PROPERTIES.csv")

In [8]:
df

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [10]:
tr = ColumnTransformer(transformers = [
    ('ohe', OneHotEncoder(drop = 'first', sparse_output = False), ['Area']),
    ('sq', SimpleImputer(strategy = 'mean'), ['Sqft']),
    ('rv', OrdinalEncoder(categories = [['Poor', 'Average', 'Good']]), ['Review'])
], remainder = 'passthrough')

In [12]:
k = tr.fit_transform(df)
print(k)
j = pd.DataFrame(k, columns = ['Area1', 'Area2', 'Sqft', 'Review', 'Price'])
j = j.map(int)
print(j)

[[1.00000000e+00 0.00000000e+00 2.60000000e+03 0.00000000e+00
  5.50000000e+05]
 [1.00000000e+00 0.00000000e+00 3.15833333e+03 1.00000000e+00
  5.65000000e+05]
 [1.00000000e+00 0.00000000e+00 3.20000000e+03 2.00000000e+00
  6.10000000e+05]
 [1.00000000e+00 0.00000000e+00 3.60000000e+03 1.00000000e+00
  6.80000000e+05]
 [1.00000000e+00 0.00000000e+00 4.00000000e+03 1.00000000e+00
  7.25000000e+05]
 [0.00000000e+00 1.00000000e+00 2.60000000e+03 2.00000000e+00
  5.85000000e+05]
 [0.00000000e+00 1.00000000e+00 2.80000000e+03 2.00000000e+00
  6.15000000e+05]
 [0.00000000e+00 1.00000000e+00 3.30000000e+03 2.00000000e+00
  6.50000000e+05]
 [0.00000000e+00 1.00000000e+00 3.60000000e+03 2.00000000e+00
  7.10000000e+05]
 [0.00000000e+00 0.00000000e+00 2.60000000e+03 0.00000000e+00
  5.75000000e+05]
 [0.00000000e+00 0.00000000e+00 2.90000000e+03 1.00000000e+00
  6.00000000e+05]
 [0.00000000e+00 0.00000000e+00 3.10000000e+03 1.00000000e+00
  6.20000000e+05]
 [0.00000000e+00 0.00000000e+00 3.60000000e+03 2.00000000e+00
  6.95000000e+05]]
    Area1  Area2  Sqft  Review   Price
0       1      0  2600       0  550000
1       1      0  3158       1  565000
2       1      0  3200       2  610000
3       1      0  3600       1  680000
4       1      0  4000       1  725000
5       0      1  2600       2  585000
6       0      1  2800       2  615000
7       0      1  3300       2  650000
8       0      1  3600       2  710000
9       0      0  2600       0  575000
10      0      0  2900       1  600000
11      0      0  3100       1  620000
12      0      0  3600       2  695000

In [13]:
# Feature Extraction
j['Mobile'] = 10
print(j)

    Area1  Area2  Sqft  Review   Price  Mobile
0       1      0  2600       0  550000      10
1       1      0  3158       1  565000      10
2       1      0  3200       2  610000      10
3       1      0  3600       1  680000      10
4       1      0  4000       1  725000      10
5       0      1  2600       2  585000      10
6       0      1  2800       2  615000      10
7       0      1  3300       2  650000      10
8       0      1  3600       2  710000      10
9       0      0  2600       0  575000      10
10      0      0  2900       1  600000      10
11      0      0  3100       1  620000      10
12      0      0  3600       2  695000      10

In [14]:
df = pd.read_csv("C:/Users/Gyanp/Downloads/retail_sales_dataset.csv")

In [15]:
df.shape

(1000, 9)

In [16]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

In [17]:
df.sample(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
135,136,2023-03-20,CUST136,Male,44,Electronics,2,300,600
885,886,2023-04-09,CUST886,Male,37,Electronics,3,300,900
364,365,2023-06-11,CUST365,Male,31,Clothing,1,300,300
528,529,2023-08-09,CUST529,Female,35,Clothing,3,50,150
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
358,359,2023-07-22,CUST359,Male,50,Clothing,1,50,50
639,640,2023-05-07,CUST640,Female,51,Electronics,4,30,120
812,813,2023-10-03,CUST813,Male,52,Electronics,3,50,150
693,694,2023-05-20,CUST694,Female,39,Electronics,2,25,50
216,217,2023-08-13,CUST217,Female,35,Electronics,4,50,200

In [18]:
df['Age'].unique()

array([34, 26, 50, 37, 30, 45, 46, 63, 52, 23, 35, 22, 64, 42, 19, 27, 47,
       62, 18, 49, 28, 38, 43, 39, 44, 51, 58, 48, 55, 20, 40, 54, 36, 31,
       21, 57, 25, 56, 29, 61, 32, 41, 59, 60, 33, 53, 24])

In [19]:
df['Age'].min()

18

In [20]:
df['Age'].max()

64

In [21]:
bn = [18, 25, 35, 55, 65]
lb = ['Young', 'Mid', 'Senior', 'Old']

In [23]:
df['Age_Group'] = pd.cut(df['Age'], bins = bn, labels = lb)

In [24]:
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Age_Group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Mid
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Mid
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Senior
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Senior
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Mid
...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,Old
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,Senior
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,Young
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,Senior
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,Senior

In [ ]:
df['Age_group'].value_counts().plot(kind = 'bar')

KeyError: 'Age_group'