- type of data type
1. Numeric data
2. Nominal data
3. Ordinal data

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("PROPERTIES - PROPERTIES.csv")
df

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

# 1. How How Big  a data is
# 2. How does the data look like
# 3. what is the data types of coloumn
# 4. Are there any missing Value 
# 5. Are there duplicates value
# 6. How does the data look like Mathematically
# 7. How is the correlation Between  columns

In [3]:
# 1. How How Big  a data is
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Area    13 non-null     object
 1   Sqft    12 non-null     float64
 2   Price   13 non-null     int64
 3   Review  13 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 548.0+ bytes

In [4]:
# 2. How does the data look like
df.head()
# df.tail()

       Area    Sqft   Price   Review
0  MP NAGAR  2600.0  550000     Poor
1  MP NAGAR     NaN  565000  Average
2  MP NAGAR  3200.0  610000     Good
3  MP NAGAR  3600.0  680000  Average
4  MP NAGAR  4000.0  725000  Average

In [5]:
# 3. what is the data types of coloumn
df.select_dtypes(exclude="O").columns

Index(['Sqft', 'Price'], dtype='object')

In [6]:
# 4. Are there any missing Value 
df.isnull().sum()

Area      0
Sqft      1
Price     0
Review    0
dtype: int64

In [7]:
# 5. Are there duplicates value
df.duplicated().sum()

np.int64(0)

In [8]:
# 6. How does the data look like Mathematically
df.describe()

              Sqft          Price
count    12.000000      13.000000
mean   3158.333333  629230.769231
std     471.859635   57621.109914
min    2600.000000  550000.000000
25%    2750.000000  585000.000000
50%    3150.000000  615000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [9]:
# 7. How is the correlation Between  columns
df.corr(numeric_only = True)

           Sqft     Price
Sqft   1.000000  0.959077
Price  0.959077  1.000000